<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/jobs/v1/job_published.proto

namespace Instapro\Events\Jobs\V1\JobPublished;

use UnexpectedValueException;

/**
 * Protobuf type <code>instapro.events.jobs.v1.JobPublished.Importance</code>
 */
class Importance
{
    /**
     * Generated from protobuf enum <code>IMPORTANCE_UNSPECIFIED = 0;</code>
     */
    const IMPORTANCE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>IMPORTANCE_ASAP = 1;</code>
     */
    const IMPORTANCE_ASAP = 1;
    /**
     * Generated from protobuf enum <code>IMPORTANCE_WHENEVER = 2;</code>
     */
    const IMPORTANCE_WHENEVER = 2;

    private static $valueToName = [
        self::IMPORTANCE_UNSPECIFIED => 'IMPORTANCE_UNSPECIFIED',
        self::IMPORTANCE_ASAP => 'IMPORTANCE_ASAP',
        self::IMPORTANCE_WHENEVER => 'IMPORTANCE_WHENEVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Importance::class, \Instapro\Events\Jobs\V1\JobPublished_Importance::class);

