<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/types/v1/attachment.proto

namespace GPBMetadata\Instapro\Types\V1;

class Attachment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ˆ
"instapro/types/v1/attachment.protoinstapro.types.v1"G

Attachment

id (	
title (	
url (	
	mime_type (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

