<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/types/v1/coordinates.proto

namespace GPBMetadata\Instapro\Types\V1;

class Coordinates
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
t
#instapro/types/v1/coordinates.protoinstapro.types.v1"2
Coordinates
latitude (
	longitude (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

