<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/talks/v1/feedback_provided.proto

namespace GPBMetadata\Instapro\Events\Talks\V1;

class FeedbackProvided
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Š
0instapro/events/talks/v1/feedback_provided.protoinstapro.events.talks.v1"4
FeedbackProvided
talk_id (
content (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

