<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/talks/v1/feedback_provided.proto

namespace Instapro\Events\Talks\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>instapro.events.talks.v1.FeedbackProvided</code>
 */
class FeedbackProvided extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 talk_id = 1;</code>
     */
    protected $talk_id = 0;
    /**
     * Generated from protobuf field <code>string content = 2;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $talk_id
     *     @type string $content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instapro\Events\Talks\V1\FeedbackProvided::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 talk_id = 1;</code>
     * @return int
     */
    public function getTalkId()
    {
        return $this->talk_id;
    }

    /**
     * Generated from protobuf field <code>int32 talk_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTalkId($var)
    {
        GPBUtil::checkInt32($var);
        $this->talk_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

}

