<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/types/v1/coordinates.proto

namespace Instapro\Types\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Geographical coordinates.
 *
 * Generated from protobuf message <code>instapro.types.v1.Coordinates</code>
 */
class Coordinates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double latitude = 1;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     */
    protected $longitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *     @type float $longitude
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instapro\Types\V1\Coordinates::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double latitude = 1;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>double latitude = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>double longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

}

