<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/jobs/v1/JobPublished.proto

namespace Instapro\Events\Service_request\V1;

if (false) {
    /**
     * This class is deprecated. Use Instapro\Events\Service_request\V1\JobPublished\Importance instead.
     * @deprecated
     */
    class JobPublished_Importance {}
}
class_exists(JobPublished\Importance::class);
@trigger_error('Instapro\Events\Service_request\V1\JobPublished_Importance is deprecated and will be removed in the next major release. Use Instapro\Events\Service_request\V1\JobPublished\Importance instead', E_USER_DEPRECATED);

