<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/jobs/v1/job_published.proto

namespace Instapro\Events\Jobs\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * New Job was published 
 *
 * Generated from protobuf message <code>instapro.events.jobs.v1.JobPublished</code>
 */
class JobPublished extends \Google\Protobuf\Internal\Message
{
    /**
     * Id of newly published job
     *
     * Generated from protobuf field <code>int32 job_id = 2;</code>
     */
    protected $job_id = 0;
    /**
     * User Id of the consumer
     *
     * Generated from protobuf field <code>int32 consumer_id = 1;</code>
     */
    protected $consumer_id = 0;
    /**
     * Id of the service
     *
     * Generated from protobuf field <code>int32 service_id = 3;</code>
     */
    protected $service_id = 0;
    /**
     * Generated from protobuf field <code>string title = 4;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>.instapro.events.jobs.v1.JobPublished.Importance importance = 6;</code>
     */
    protected $importance = 0;
    /**
     * Generated from protobuf field <code>.instapro.types.v1.Coordinates coordinates = 7;</code>
     */
    protected $coordinates = null;
    /**
     * Generated from protobuf field <code>map<string, .instapro.types.v1.Attachment> images = 8;</code>
     */
    private $images;
    /**
     * Generated from protobuf field <code>repeated .instapro.types.v1.Attachment files = 23;</code>
     */
    private $files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $job_id
     *           Id of newly published job
     *     @type int $consumer_id
     *           User Id of the consumer
     *     @type int $service_id
     *           Id of the service
     *     @type string $title
     *     @type int $importance
     *     @type \Instapro\Types\V1\Coordinates $coordinates
     *     @type array|\Google\Protobuf\Internal\MapField $images
     *     @type \Instapro\Types\V1\Attachment[]|\Google\Protobuf\Internal\RepeatedField $files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instapro\Events\Jobs\V1\JobPublished::initOnce();
        parent::__construct($data);
    }

    /**
     * Id of newly published job
     *
     * Generated from protobuf field <code>int32 job_id = 2;</code>
     * @return int
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Id of newly published job
     *
     * Generated from protobuf field <code>int32 job_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkInt32($var);
        $this->job_id = $var;

        return $this;
    }

    /**
     * User Id of the consumer
     *
     * Generated from protobuf field <code>int32 consumer_id = 1;</code>
     * @return int
     */
    public function getConsumerId()
    {
        return $this->consumer_id;
    }

    /**
     * User Id of the consumer
     *
     * Generated from protobuf field <code>int32 consumer_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setConsumerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->consumer_id = $var;

        return $this;
    }

    /**
     * Id of the service
     *
     * Generated from protobuf field <code>int32 service_id = 3;</code>
     * @return int
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Id of the service
     *
     * Generated from protobuf field <code>int32 service_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt32($var);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.instapro.events.jobs.v1.JobPublished.Importance importance = 6;</code>
     * @return int
     */
    public function getImportance()
    {
        return $this->importance;
    }

    /**
     * Generated from protobuf field <code>.instapro.events.jobs.v1.JobPublished.Importance importance = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setImportance($var)
    {
        GPBUtil::checkEnum($var, \Instapro\Events\Jobs\V1\JobPublished\Importance::class);
        $this->importance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.instapro.types.v1.Coordinates coordinates = 7;</code>
     * @return \Instapro\Types\V1\Coordinates|null
     */
    public function getCoordinates()
    {
        return $this->coordinates;
    }

    public function hasCoordinates()
    {
        return isset($this->coordinates);
    }

    public function clearCoordinates()
    {
        unset($this->coordinates);
    }

    /**
     * Generated from protobuf field <code>.instapro.types.v1.Coordinates coordinates = 7;</code>
     * @param \Instapro\Types\V1\Coordinates $var
     * @return $this
     */
    public function setCoordinates($var)
    {
        GPBUtil::checkMessage($var, \Instapro\Types\V1\Coordinates::class);
        $this->coordinates = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .instapro.types.v1.Attachment> images = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>map<string, .instapro.types.v1.Attachment> images = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Instapro\Types\V1\Attachment::class);
        $this->images = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .instapro.types.v1.Attachment files = 23;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .instapro.types.v1.Attachment files = 23;</code>
     * @param \Instapro\Types\V1\Attachment[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Instapro\Types\V1\Attachment::class);
        $this->files = $arr;

        return $this;
    }

}

