<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instapro/events/jobs/v1/JobPublished.proto

namespace Instapro\Events\Service_request\V1\JobPublished;

use UnexpectedValueException;

/**
 * Protobuf type <code>instapro.events.service_request.v1.JobPublished.Importance</code>
 */
class Importance
{
    /**
     * Generated from protobuf enum <code>ASAP = 0;</code>
     */
    const ASAP = 0;
    /**
     * Generated from protobuf enum <code>WHENEVER = 1;</code>
     */
    const WHENEVER = 1;

    private static $valueToName = [
        self::ASAP => 'ASAP',
        self::WHENEVER => 'WHENEVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Importance::class, \Instapro\Events\Service_request\V1\JobPublished_Importance::class);

